"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let places = ['Pakistan', 'China', 'Canada', 'Dubi', 'India', 'Afghanistan'];
console.log('Original order:', places);
console.log('Reverse order:', [...places].reverse());
console.log('Original order:', places);
console.log('Alphabetical order:', [...places].sort());
console.log('Original order:', places);
console.log('Reverse alphabetical order:', [...places].sort().reverse());
console.log('Originale order:', places);
places.reverse();
console.log('Reverse order:', places);
places.reverse();
console.log('Original order:', places);
places.sort();
console.log('Alphabetical order', places);
places.reverse();
console.log('Reverse alphabetical order:', places);
